name: CD to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy code and install requirements
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          set -e
          cd /home/ubuntu/my_works_2
          git pull origin main
          if [ ! -d "venv" ]; then python3 -m venv venv; fi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pkill uvicorn || true
        '

    - name: Start FastAPI app
      run: |
        ssh -f ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/my_works_2 &&
          source venv/bin/activate &&
          nohup uvicorn app.main:fast_app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 & sleep 1; disown
        "
