name: CD to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e  # hata olursa dur

          echo "[INFO] Updating system packages"
          sudo apt update

          echo "[INFO] Installing Python 3.11 and tools if missing"
          if ! command -v python3.11 &> /dev/null; then
            sudo apt install -y software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa -y
            sudo apt install python3-apt -y
            sudo apt install -y python3.11 python3.11-venv python3.11-distutils curl
            curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.11
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
            sudo update-alternatives --set python3 /usr/bin/python3.11
          fi

          echo "[INFO] Installing pip if missing"
          if ! command -v pip &> /dev/null; then
            curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
          fi

          echo "[INFO] Navigating to project directory"
          cd /home/ubuntu/my_works_2

          echo "[INFO] Pulling latest code"
          git pull origin main

          echo "[INFO] Creating venv if not exists"
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          echo "[INFO] Activating venv and installing requirements"
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "[INFO] Killing any existing uvicorn process"
          pkill uvicorn || true


          echo "[INFO] Starting FastAPI app"
          nohup uvicorn app.main:fast_app --host 0.0.0.0 --port 8000 &
        EOF
